package main

func typecheck(.., .., values ... interface{}) {
for _, value := range values {
switch v := value.(type) {
case int: ...
case float: ...
case string: ...
case bool: ...
default: ...
}
}
}
